os: linux
dist: jammy
sudo: required

language: node_js
node_js:
  - '16.17.0'
cache:
  yarn: true
  directories:
    - node_modules

services:
  - xvfb

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > $HOME/.npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.19
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn test
